const sampleData = [
  {
    id: 23,
    createdAt: '2018-05-15T07:00:00.000Z',
    userRating: 0,
    wasFoodGood: 0,
    wasDeliveredOnTime: 0,
    wasOrderAccurate: 0,
    reviewMsg: 'Sit delectus est eveniet omnis eius.',
    userId: 3,
    restaurantId: 9,
    username: 'Lavern.Boyle',
    reviewsCount: 14,
    items: [
      {
        id: 11,
        reviewId: 23,
        itemId: 11,
        itemName: 'Pretzel',
        iDescription: 'Nihil debitis aut a similique saepe rerum unde.',
        price: 364,
      },
      {
        id: 22,
        reviewId: 23,
        itemId: 22,
        itemName: 'Ramen',
        iDescription: 'Ullam numquam adipisci laudantium dolor delectus.',
        price: 795,
      },
      {
        id: 18,
        reviewId: 23,
        itemId: 18,
        itemName: 'Chilli',
        iDescription: 'Voluptatem ut enim ut modi.',
        price: 692,
      },
      {
        id: 13,
        reviewId: 23,
        itemId: 13,
        itemName: 'Beef Taco',
        iDescription: 'Minus neque consequuntur quas voluptatum.',
        price: 892,
      },
      {
        id: 17,
        reviewId: 23,
        itemId: 17,
        itemName: 'Soft Pork Taco',
        iDescription: 'Perspiciatis aut voluptatum voluptatem.',
        price: 857,
      },
      {
        id: 17,
        reviewId: 23,
        itemId: 17,
        itemName: 'Soft Pork Taco',
        iDescription: 'Perspiciatis aut voluptatum voluptatem.',
        price: 857,
      },
      {
        id: 4,
        reviewId: 23,
        itemId: 4,
        itemName: 'Peperonie Pizza',
        iDescription: 'Ducimus non et corporis eos.',
        price: 878,
      },
      {
        id: 20,
        reviewId: 23,
        itemId: 20,
        itemName: 'Carbonara Pasta',
        iDescription: 'Incidunt dolores non quae amet provident nulla deleniti.',
        price: 618,
      },
    ],
  },
  {
    id: 34,
    createdAt: '2018-10-18T07:00:00.000Z',
    userRating: 2,
    wasFoodGood: 0,
    wasDeliveredOnTime: 0,
    wasOrderAccurate: 1,
    reviewMsg: 'Dolorem alias a quia eveniet libero ducimus placeat.',
    userId: 5,
    restaurantId: 9,
    username: 'Royce_Treutel',
    reviewsCount: 12,
    items: [
      {
        id: 25,
        reviewId: 34,
        itemId: 25,
        itemName: 'Boba tea',
        iDescription: 'Ut quaerat excepturi.',
        price: 694,
      },
      {
        id: 6,
        reviewId: 34,
        itemId: 6,
        itemName: 'French Fries',
        iDescription: 'Repudiandae tenetur maxime nobis vitae facilis.',
        price: 799,
      },
      {
        id: 21,
        reviewId: 34,
        itemId: 21,
        itemName: 'Nodles',
        iDescription: 'Dolorem impedit incidunt qui veniam.',
        price: 30,
      },
      {
        id: 19,
        reviewId: 34,
        itemId: 19,
        itemName: 'Sushi',
        iDescription: 'Assumenda nulla ipsa repudiandae qui debitis eos.',
        price: 795,
      },
      {
        id: 5,
        reviewId: 34,
        itemId: 5,
        itemName: 'Chicken Sandwich',
        iDescription: 'Perspiciatis tenetur excepturi architecto.',
        price: 895,
      },
      {
        id: 24,
        reviewId: 34,
        itemId: 24,
        itemName: 'Spicy Chicken Sandwich',
        iDescription: 'Dolor earum nulla.',
        price: 633,
      },
      {
        id: 16,
        reviewId: 34,
        itemId: 16,
        itemName: 'Chicken Biscuit',
        iDescription: 'Ipsam architecto eos non mollitia quasi praesentium expedita est.',
        price: 442,
      },
      {
        id: 24,
        reviewId: 34,
        itemId: 24,
        itemName: 'Spicy Chicken Sandwich',
        iDescription: 'Dolor earum nulla.',
        price: 633,
      },
      {
        id: 24,
        reviewId: 34,
        itemId: 24,
        itemName: 'Spicy Chicken Sandwich',
        iDescription: 'Dolor earum nulla.',
        price: 633,
      },
      {
        id: 20,
        reviewId: 34,
        itemId: 20,
        itemName: 'Carbonara Pasta',
        iDescription: 'Incidunt dolores non quae amet provident nulla deleniti.',
        price: 618,
      },
      {
        id: 15,
        reviewId: 34,
        itemId: 15,
        itemName: 'Cajun Fries',
        iDescription: 'Sapiente vel occaecati quasi.',
        price: 618,
      },
      {
        id: 14,
        reviewId: 34,
        itemId: 14,
        itemName: 'Ceasar Salad',
        iDescription: 'Nihil quibusdam accusantium.',
        price: 856,
      },
      {
        id: 21,
        reviewId: 34,
        itemId: 21,
        itemName: 'Nodles',
        iDescription: 'Dolorem impedit incidunt qui veniam.',
        price: 30,
      },
      {
        id: 11,
        reviewId: 34,
        itemId: 11,
        itemName: 'Pretzel',
        iDescription: 'Nihil debitis aut a similique saepe rerum unde.',
        price: 364,
      },
      {
        id: 9,
        reviewId: 34,
        itemId: 9,
        itemName: 'Orange Juice',
        iDescription: 'Atque illo aliquid consequatur nihil qui animi quod eaque beatae.',
        price: 82,
      },
      {
        id: 23,
        reviewId: 34,
        itemId: 23,
        itemName: 'Chicken Wings',
        iDescription: 'In qui aut autem quia aut blanditiis.',
        price: 904,
      },
      {
        id: 3,
        reviewId: 34,
        itemId: 3,
        itemName: 'Bacon Cheese',
        iDescription: 'Unde iste nemo.',
        price: 504,
      },
    ],
  },
  {
    id: 87,
    createdAt: '2018-08-26T07:00:00.000Z',
    userRating: 4,
    wasFoodGood: 1,
    wasDeliveredOnTime: 1,
    wasOrderAccurate: 0,
    reviewMsg: 'Non maxime qui aut.',
    userId: 9,
    restaurantId: 9,
    username: 'Cheyanne_Gottlieb',
    reviewsCount: 12,
    items: [
      {
        id: 5,
        reviewId: 87,
        itemId: 5,
        itemName: 'Chicken Sandwich',
        iDescription: 'Perspiciatis tenetur excepturi architecto.',
        price: 895,
      },
      {
        id: 4,
        reviewId: 87,
        itemId: 4,
        itemName: 'Peperonie Pizza',
        iDescription: 'Ducimus non et corporis eos.',
        price: 878,
      },
      {
        id: 21,
        reviewId: 87,
        itemId: 21,
        itemName: 'Nodles',
        iDescription: 'Dolorem impedit incidunt qui veniam.',
        price: 30,
      },
      {
        id: 19,
        reviewId: 87,
        itemId: 19,
        itemName: 'Sushi',
        iDescription: 'Assumenda nulla ipsa repudiandae qui debitis eos.',
        price: 795,
      },
      {
        id: 9,
        reviewId: 87,
        itemId: 9,
        itemName: 'Orange Juice',
        iDescription: 'Atque illo aliquid consequatur nihil qui animi quod eaque beatae.',
        price: 82,
      },
      {
        id: 17,
        reviewId: 87,
        itemId: 17,
        itemName: 'Soft Pork Taco',
        iDescription: 'Perspiciatis aut voluptatum voluptatem.',
        price: 857,
      },
      {
        id: 17,
        reviewId: 87,
        itemId: 17,
        itemName: 'Soft Pork Taco',
        iDescription: 'Perspiciatis aut voluptatum voluptatem.',
        price: 857,
      },
      {
        id: 18,
        reviewId: 87,
        itemId: 18,
        itemName: 'Chilli',
        iDescription: 'Voluptatem ut enim ut modi.',
        price: 692,
      },
      {
        id: 12,
        reviewId: 87,
        itemId: 12,
        itemName: 'Kitava',
        iDescription: 'Omnis itaque explicabo odio aut veritatis voluptatem sunt porro.',
        price: 834,
      },
      {
        id: 9,
        reviewId: 87,
        itemId: 9,
        itemName: 'Orange Juice',
        iDescription: 'Atque illo aliquid consequatur nihil qui animi quod eaque beatae.',
        price: 82,
      },
      {
        id: 15,
        reviewId: 87,
        itemId: 15,
        itemName: 'Cajun Fries',
        iDescription: 'Sapiente vel occaecati quasi.',
        price: 618,
      },
      {
        id: 23,
        reviewId: 87,
        itemId: 23,
        itemName: 'Chicken Wings',
        iDescription: 'In qui aut autem quia aut blanditiis.',
        price: 904,
      },
      {
        id: 6,
        reviewId: 87,
        itemId: 6,
        itemName: 'French Fries',
        iDescription: 'Repudiandae tenetur maxime nobis vitae facilis.',
        price: 799,
      },
      {
        id: 24,
        reviewId: 87,
        itemId: 24,
        itemName: 'Spicy Chicken Sandwich',
        iDescription: 'Dolor earum nulla.',
        price: 633,
      },
      {
        id: 23,
        reviewId: 87,
        itemId: 23,
        itemName: 'Chicken Wings',
        iDescription: 'In qui aut autem quia aut blanditiis.',
        price: 904,
      },
      {
        id: 18,
        reviewId: 87,
        itemId: 18,
        itemName: 'Chilli',
        iDescription: 'Voluptatem ut enim ut modi.',
        price: 692,
      },
    ],
  },
];

export default sampleData;
