const restaurants = [
  'Litte Kite',
  'Big Latern',
  'Yama Sushi',
  'Soma Pizza',
  'Mr. Pizza Pan',
  'Cheers Market',
  'Milan Pizza',
  'Platform 248',
  'Tuans Kitchen',
  'SUBWAY',
  'Mac Daddy',
  'Kitava',
  'Pacho Villa',
  'Boston Market',
  'All Star Cafe',
  'Mr. Pizza Man',
  'V Cafe',
  'Red Jade Restaurant',
  'Big Mouth Burguer',
  'El Toro Taqueria',
  'El Metate',
  'Umami Burger',
  'KFC',
  'Laksa',
  'Jasmin Tea House',
  'We Be Sushi',
  'Pink Onion',
];

const menu = [
  'Wafles Fries',
  'Cheese Burger',
  'Bacon Cheese',
  'Peperonie Pizza',
  'Chicken Sandwich',
  'French Fries',
  'Ice Cream',
  'Coffe',
  'Orange Juice',
  'Nuggets',
  'Pretzel',
  'Kitava',
  'Beef Taco',
  'Ceasar Salad',
  'Cajun Fries',
  'Chicken Biscuit',
  'Soft Pork Taco',
  'Chilli',
  'Sushi',
  'Carbonara Pasta',
  'Nodles',
  'Ramen',
  'Chicken Wings',
  'Spicy Chicken Sandwich',
  'Boba tea',
  'Green Tea',
  'Onion Soup',
];

module.exports = {
  restaurants,
  menu,
};
