const restaurants = [
'Litte Kite',
'Big Latern',
'Yama Sushi',
'Soma Pizza',
'Mr. Pizza Pan',
'Cheers Market',
'Milan Pizza',
'Platform 248',
'Tuans Kitchen',
'SUBWAY',
'Mac Daddy',
'Kitava',
'Pacho Villa',
'Boston Market',
'All Star Cafe',
'Mr. Pizza Man',
'V Cafe',
'Red Jade Restaurant',
'Big Mouth Burguer',
'El Toro Taqueria',
'El Metate',
'Umami Burger',
'KFC',
'Laksa',
'Jasmin Tea House',
'We Be Sushi',
'Pink Onion'
];

module.exports.restaurants = restaurants;